name: Build Gradle project


on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      #- name: Setup Gradle
      #  uses: actions/setup-java@v3
      #  with:
      #    distribution: 'oracle'
      #    java-version: '17'
      #    cache: 'gradle'
      #- run: sh gradlew build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create JAR file
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
      - run: sh gradlew jar

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::CryptoLibBuild_$(date +"%Y.%m.%d_%H-%M")"

      - name: Release the JAR file
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: build/libs/crypto.jar
          token: ${{ secrets.GITHUB_TOKEN }}
