name: Build Gradle project


on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
      - run: sh gradlew build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create JAR file
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
      - run: sh gradlew jar

      - name: Generate release tag
        id: tag
        run: |
          echo "tag=CryptoLibBuild_$(date + "%Y.%m.%d_%H-%M")" >> "$GITHUB_ENV"

      - name: Release the JAR file
        uses: softprops/action-gh-release@v2
        with:
          tag_name: $tag
          files: build/libs/crypto.jar
          token: ${{ secrets.GITHUB_TOKEN }}
